# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Illia Yakovenko
email: iykvnk@gmail.com
description: > # this means to ignore newlines until "baseurl:" 
  a precarious cultural worker, a self-proclaimed artist, curator, poet and spectator, an unrecognized cultural diplomat. In his artistic practice, he reexamines the historical, social, economic and political conditions of art production and the influence that state cultural policies have on it. He deals with issues related to history, memory, culture, identity, and their byproducts such as exclusion, othering, marginalization, and stigmatization by means of collective and participatory production of art. He is a member of the Cooperative for Creative Research Krasnaya Shpana and تعاونية artistic cooperative. Lives and works between Kiev and Kyiv.

baseurl: "" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

permalink:    /:title
# paginate:     3
#
# gems:
#   - jekyll-sitemap
#   - jekyll-paginate
