# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: radical artistic research
email: somewhere@onenetbeyond.org
description: > # this means to ignore newlines until "baseurl:"
  Places: Mariupol, Donetsk, Moscow, Beirut, Kyiv.
  Institutions: ICA Moscow, Chto Delat's School for Engaged Art, Ashkal Alwan HWP program.
  Member of the co-operative for creative reseach "Krasnaya Shpana" (Hamburg-Kyiv-Moscow) and Tawaaniya co-operative (Beirut-Istanbul-Kyiv-New-York)

baseurl: "" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

permalink:    /:title
# paginate:     3
#
# gems:
#   - jekyll-sitemap
#   - jekyll-paginate
